version: '2'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    command: --rest --httpinterface

  mongo-express:
    image: mongo-express
    links:
      - mongo
    ports:
      - "8081:8081"

volumes:
  mongo_data:
    driver: local
